# Generated by Django 6.0.6 on 2026-06-10 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='correct_answer_index',
        ),
        migrations.RemoveField(
            model_name='session',
            name='lecture_content',
        ),
        migrations.RemoveField(
            model_name='session',
            name='passed_quiz',
        ),
        migrations.RemoveField(
            model_name='session',
            name='quiz_options',
        ),
        migrations.RemoveField(
            model_name='session',
            name='quiz_question',
        ),
        migrations.RemoveField(
            model_name='session',
            name='student_answer_index',
        ),
        migrations.RemoveField(
            model_name='session',
            name='topic',
        ),
        migrations.AddField(
            model_name='session',
            name='current_topic_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='topics',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='session',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TopicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('topic_index', models.IntegerField(default=0)),
                ('intro_content', models.TextField(blank=True)),
                ('lecture_content', models.TextField(blank=True)),
                ('quiz_question', models.TextField(blank=True)),
                ('quiz_options', models.JSONField(default=list)),
                ('correct_answer_index', models.IntegerField(default=0)),
                ('student_answer_index', models.IntegerField(blank=True, null=True)),
                ('passed_quiz', models.BooleanField(default=False)),
                ('xp_earned', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_sessions', to='core.session')),
            ],
            options={
                'ordering': ['topic_index'],
            },
        ),
    ]
