# Generated by Django 6.0.6 on 2026-06-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_session_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3)),
                ('file', models.FileField(upload_to='outlines/')),
                ('extracted_text', models.TextField(blank=True)),
                ('topics_json', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('course_code', 'level')},
            },
        ),
    ]
