# Generated by Django 6.0.6 on 2026-06-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_topicsession_quiz_explanation_challenge_exam_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('petroleum', 'Petroleum & Gas Engineering')], default='petroleum', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(choices=[('unilag', 'University of Lagos')], default='unilag', max_length=50),
        ),
    ]
