# Generated by Django 6.0.6 on 2026-06-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studentprofile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3)),
                ('file', models.FileField(upload_to='past_questions/')),
                ('extracted_text', models.TextField(blank=True)),
                ('parsed_questions', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['course_code', '-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='slidedocument',
            options={'ordering': ['course_code']},
        ),
        migrations.AlterUniqueTogether(
            name='slidedocument',
            unique_together={('course_code', 'level')},
        ),
        migrations.AddField(
            model_name='slidedocument',
            name='extracted_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='slidedocument',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='slidedocument',
            name='week_number',
        ),
    ]
