# Generated by Django 6.0.6 on 2026-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pastquestion_alter_slidedocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidedocument',
            options={'ordering': ['course_code', 'week_number']},
        ),
        migrations.AlterUniqueTogether(
            name='slidedocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='slidedocument',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slidedocument',
            name='level',
            field=models.CharField(blank=True, choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='slidedocument',
            unique_together={('course_code', 'level', 'week_number')},
        ),
    ]
