# Generated by Django 6.0.6 on 2026-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_slidedocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3)),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], max_length=1)),
                ('school', models.CharField(choices=[('unilag', 'University of Lagos')], default='unilag', max_length=50)),
                ('department', models.CharField(choices=[('petroleum', 'Petroleum & Gas Engineering')], default='petroleum', max_length=50)),
                ('units', models.IntegerField(default=3)),
                ('is_elective', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['level', 'semester', 'is_elective', 'course_code'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='elective_courses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_elective': True}, related_name='enrolled_students', to='core.coursedefinition'),
        ),
    ]
