# Generated by Django 6.0.6 on 2026-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coursedefinition_studentprofile_elective_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
    ]
