# Generated by Django 6.0.6 on 2026-07-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentprofile_is_staff_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage_set', to='core.topicsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
