# Generated by Django 6.0.6 on 2026-08-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidedocument',
            options={'ordering': ['course_code']},
        ),
        migrations.AlterUniqueTogether(
            name='slidedocument',
            unique_together={('course_code', 'level')},
        ),
        migrations.AlterField(
            model_name='slidedocument',
            name='file',
            field=models.FileField(max_length=500, upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='slidedocument',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=300, max_length=3),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='slidedocument',
            name='week_number',
        ),
    ]
