# Generated by Django 6.0.6 on 2026-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_slidedocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
