# Generated by Django 6.0.6 on 2026-09-04 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chatmessage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('auto', 'Automatic Test Week'), ('voluntary', 'Voluntary Practice Test')], default='voluntary', max_length=10)),
                ('question_format', models.CharField(choices=[('mcq', 'Multiple Choice'), ('theory', 'Theory / Calculation'), ('mixed', 'Mixed')], default='theory', max_length=10)),
                ('week_number', models.IntegerField(default=1)),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('ai_feedback', models.JSONField(default=list)),
                ('overall_feedback', models.TextField(blank=True)),
                ('percentage_score', models.FloatField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulator_tests', to='core.studentprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
