# Generated by Django 6.0.6 on 2026-09-05 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_simulatortest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreGeneratedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('topic_title', models.CharField(max_length=200)),
                ('content_chunk', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.coursedefinition')),
            ],
            options={
                'ordering': ['week_number', 'topic_title'],
                'unique_together': {('course', 'week_number', 'topic_title')},
            },
        ),
    ]
