# Generated by Django 6.0.6 on 2026-09-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pregeneratedlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('chunk_text', models.TextField(blank=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.slidedocument')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('slide', 'week_number')},
            },
        ),
    ]
