# Generated by Django 6.0.6 on 2026-09-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_slidechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='queue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='queue_position',
            field=models.IntegerField(default=0),
        ),
    ]
