# Generated by Django 6.0.6 on 2026-09-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_studentprofile_queue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
