# Generated by Django 6.0.6 on 2026-09-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_topicsession_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='total_weeks',
            field=models.IntegerField(default=10),
        ),
    ]
