# Generated by Django 6.0.6 on 2026-09-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_timetableentry_total_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_pregenerated',
            field=models.BooleanField(default=False),
        ),
    ]
