# Generated by Django 6.0.6 on 2026-09-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_chatmessage_is_pregenerated'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsession',
            name='chunks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='topicsession',
            name='current_chunk_index',
            field=models.IntegerField(default=0),
        ),
    ]
