# Generated by Django 6.0.6 on 2026-09-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_topicsession_chunks_topicsession_current_chunk_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidedocument',
            name='topics_incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
