# Generated by Django 6.0.6 on 2026-09-08 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_slidedocument_topics_incomplete'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideExtractionChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('chunk_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('extracted_topics', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_chunks', to='core.slidedocument')),
            ],
            options={
                'ordering': ['chunk_index'],
                'unique_together': {('slide', 'chunk_index')},
            },
        ),
    ]
