# Generated by Django 6.0.6 on 2026-09-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_slideextractionchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregeneratedlesson',
            name='continuation_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregeneratedlesson',
            name='is_truncated',
            field=models.BooleanField(default=False),
        ),
    ]
