# Generated by Django 6.0.6 on 2026-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_pregeneratedlesson_continuation_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidedocument',
            name='append_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='slidedocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='slides/'),
        ),
    ]
