# Generated by Django 6.0.6 on 2026-09-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_slidedocument_append_count_alter_slidedocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideTopicChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('topic_name', models.CharField(max_length=200)),
                ('chunk_text', models.TextField(blank=True)),
                ('is_empty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_chunks', to='core.slidedocument')),
            ],
            options={
                'ordering': ['week_number', 'topic_name'],
                'unique_together': {('slide', 'week_number', 'topic_name')},
            },
        ),
    ]
