# Generated by Django 6.0.6 on 2026-09-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_slidecleanupchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideTopicSplitChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('chunk_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('split_result', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_split_chunks', to='core.slidedocument')),
            ],
            options={
                'ordering': ['chunk_index'],
                'unique_together': {('slide', 'chunk_index')},
            },
        ),
    ]
