# Generated by Django 6.0.6 on 2026-10-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_slidetopicsplitchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorBankTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3)),
                ('topic_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NO_SOURCE', 'No lecture or slide content yet')], default='PENDING', max_length=10)),
                ('source_type', models.CharField(blank=True, max_length=10)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('mcq_saved', models.PositiveSmallIntegerField(default=0)),
                ('long_saved', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_code', 'topic_name'],
                'unique_together': {('course_code', 'level', 'topic_name')},
            },
        ),
        migrations.CreateModel(
            name='SimulatorQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_index=True, max_length=10)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3)),
                ('topic_name', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice'), ('theory', 'Theory'), ('calculation', 'Calculation')], max_length=12)),
                ('cognitive_level', models.CharField(blank=True, max_length=12)),
                ('marks', models.PositiveSmallIntegerField(default=2)),
                ('content', models.JSONField(default=dict)),
                ('source_type', models.CharField(choices=[('lecture', 'Published lecture'), ('slide', 'Slide topic chunk')], max_length=10)),
                ('source_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('retired', 'Retired')], default='pending_review', max_length=16)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_code', 'topic_name', 'question_type', 'id'],
                'indexes': [models.Index(fields=['course_code', 'level', 'topic_name', 'status'], name='core_simula_course__5793d0_idx')],
            },
        ),
    ]
