# Generated by Django 6.0.6 on 2026-10-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_simulatorbanktopic_simulatorquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='study_days',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
