# Generated by Django 6.0.6 on 2026-10-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_timetableentry_study_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='test_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
