# Generated by Django 6.0.6 on 2026-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_timetableentry_test_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregeneratedlesson',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pregeneratedlesson',
            name='source_type',
            field=models.CharField(choices=[('slides', 'Lecturer slides'), ('outline', 'Course outline only')], default='slides', max_length=10),
        ),
    ]
