# Generated by Django 6.0.6 on 2026-10-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pregeneratedlesson_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregeneratedlesson',
            name='quiz',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pregeneratedlesson',
            name='quiz_source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
