# Generated by Django 6.0.6 on 2026-09-27 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_slidetopicsplitchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed — doubled'), ('stopped_voluntary', 'Stopped by student — no strikes'), ('stopped_after_strike', 'Stopped by student — after a strike')], default='active', max_length=25)),
                ('stake_initial', models.PositiveIntegerField()),
                ('stake_current', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_duration_seconds', models.PositiveIntegerField()),
                ('target_ends_at', models.DateTimeField()),
                ('away_started_at', models.DateTimeField(blank=True, null=True)),
                ('away_budget_used_seconds', models.PositiveIntegerField(default=0)),
                ('strikes_count', models.PositiveSmallIntegerField(default=0)),
                ('awaiting_strike_decision', models.BooleanField(default=False)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('final_xp_awarded', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sprints', to='core.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FocusSprintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('away_detected', 'Went away'), ('returned', 'Returned'), ('strike', 'Strike — stake halved'), ('continued_after_strike', 'Continued after strike'), ('stopped_voluntary', 'Stopped voluntarily'), ('stopped_after_strike', 'Stopped after strike'), ('completed', 'Completed — doubled')], max_length=25)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='focus_sprint.focussprint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='focussprint',
            index=models.Index(fields=['student', 'status'], name='focus_sprin_student_293b92_idx'),
        ),
        migrations.AddConstraint(
            model_name='focussprint',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='uniq_active_focus_sprint_per_student'),
        ),
    ]
