# Generated by Django 6.0.6 on 2026-09-24 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_slidetopicsplitchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tts_seconds', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='core.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='engagement__date_ff3a84_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='uniq_daily_activity')],
            },
        ),
        migrations.CreateModel(
            name='ModuleDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tts_seconds', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_code', models.CharField(max_length=10)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('topic_name', models.CharField(max_length=200)),
                ('read_seconds', models.PositiveIntegerField(default=0)),
                ('tts_plays', models.PositiveIntegerField(default=0)),
                ('tts_completions', models.PositiveIntegerField(default=0)),
                ('parts_viewed', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='core.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['course_code', 'week_number', 'topic_name'], name='engagement__course__cdcab3_idx'), models.Index(fields=['date'], name='engagement__date_b6689e_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date', 'course_code', 'week_number', 'topic_name'), name='uniq_module_daily')],
            },
        ),
    ]
