from django.urls import path
from core import views

urlpatterns = [
    path("", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
    path("logout/", views.logout_view, name="logout"),
    path("onboarding/", views.onboarding_view, name="onboarding"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("session/<str:course_code>/", views.session_view, name="session"),
    path("quiz/<int:topic_session_id>/", views.quiz_view, name="quiz"),
    path("answer/", views.answer_view, name="answer"),
    path("next-topic/", views.next_topic_view, name="next_topic"),
    path("leaderboard/", views.leaderboard_view, name="leaderboard"),
    path("timetable/", views.timetable_view, name="timetable"),
    path("reschedule/<int:entry_id>/", views.reschedule_session, name="reschedule"),
    path("profile/edit/", views.profile_edit_view, name="profile_edit"),
    path("review/<int:topic_session_id>/", views.review_view, name="review"),
    path("history/", views.history_view, name="history"),
    path("session/<str:course_code>/restart/<int:week_number>/", views.restart_session_view, name="restart_session"),
    path("electives/", views.elective_selection_view, name="elective_selection"),
    path("courses/manage/", views.manage_courses_view, name="manage_courses"),
    path("staff/", views.staff_portal_view, name="staff_portal"),
    path("staff/slides/upload/", views.staff_upload_slide_view, name="staff_upload_slide"),
    path("staff/outline/upload/", views.staff_upload_outline_view, name="staff_upload_outline"),
    path("staff/past-questions/upload/", views.staff_upload_past_questions_view, name="staff_upload_past_questions"),
    path("staff/courses/", views.staff_manage_courses_view, name="staff_manage_courses"),
    path("staff/courses/delete/<int:course_id>/", views.staff_delete_course_view, name="staff_delete_course"),
    path('staff/slides/delete/<int:slide_id>/', views.delete_slide, name='delete_slide'),
    path('staff/slides/retry-topics/<int:slide_id>/', views.retry_slide_topics_view, name='retry_slide_topics'),
    path('staff/outlines/delete/<int:outline_id>/', views.delete_outline_view, name='delete_outline'),
    path('staff/past-questions/delete/<int:question_id>/', views.delete_past_question, name='delete_past_question'),
    path('staff/courses/delete/<int:course_id>/', views.delete_course_definition, name='delete_course_definition'),
    path("chat/message/", views.chat_message_view, name="chat_message"),
    path("chat/next-topic/", views.chat_next_topic_view, name="chat_next_topic"),
    path("course/<str:course_code>/outline/", views.course_outline_view, name="course_outline"),
    path("siwes/", views.siwes_view, name="siwes"),
    path("courses/manage/", views.manage_courses_view, name="manage_courses"),
]