# Generated by Django 6.0.6 on 2026-09-17 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_slidetopicsplitchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('alternating', 'Alternating'), ('buzzer', 'Buzzer')], max_length=15)),
                ('team_a_score', models.IntegerField(default=0)),
                ('team_b_score', models.IntegerField(default=0)),
                ('winner', models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, null=True)),
                ('ended_by_disconnect', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('level', models.CharField(choices=[('300', '300 Level'), ('400', '400 Level')], max_length=3)),
                ('question_type', models.CharField(choices=[('static', 'Static'), ('template', 'Template')], default='static', max_length=10)),
                ('stem', models.TextField()),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('retired', 'Retired')], default='pending_review', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_chunk', models.ForeignKey(blank=True, help_text='Traceability back to the slide content this question was generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_questions', to='core.slidetopicchunk')),
            ],
            options={
                'ordering': ['course_code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleMatchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('served_stem', models.TextField()),
                ('served_options_snapshot', models.JSONField(default=list, help_text='Exact options shown, in the exact order shown, with which index was correct.')),
                ('is_bonus', models.BooleanField(default=False)),
                ('answering_team', models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, null=True)),
                ('answer_given_index', models.IntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('answering_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_answers', to='core.studentprofile')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_questions', to='battle.battlematch')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_appearances', to='battle.battlequestion')),
            ],
            options={
                'ordering': ['match', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='BattleAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='battle.battlequestion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BattleQuestionGenerationChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('questions_generated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_generation_chunks', to='core.slidetopicchunk')),
            ],
        ),
        migrations.CreateModel(
            name='BattleQuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_description', models.TextField(help_text='Human-readable description of the governing equation, for staff review.')),
                ('variable_ranges', models.JSONField(default=dict, help_text='e.g. {"q": {"min": 100, "max": 2000, "unit": "STB/d"}, "dp": {"min": 50, "max": 500, "unit": "psi"}}')),
                ('correct_computation', models.CharField(help_text="Named rule the generation/serve code knows how to evaluate, e.g. 'productivity_index'.", max_length=100)),
                ('wrong_computations', models.JSONField(default=list, help_text="List of named wrong-operation rules to generate distractors from, e.g. ['invert_ratio', 'wrong_unit_conversion'].")),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='battle.battlequestion')),
            ],
        ),
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('mode', models.CharField(blank=True, choices=[('alternating', 'Alternating'), ('buzzer', 'Buzzer')], max_length=15, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_battle_rooms', to='core.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, null=True)),
                ('role', models.CharField(choices=[('player', 'Player'), ('spectator', 'Spectator')], default='player', max_length=10)),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='connected', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to='core.studentprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='battle.battleroom')),
            ],
        ),
        migrations.AddField(
            model_name='battlematch',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='battle.battleroom'),
        ),
        migrations.CreateModel(
            name='StudentQuestionExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='battle.battlequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_exposures', to='core.studentprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='battlequestion',
            index=models.Index(fields=['course_code', 'level', 'status'], name='battle_batt_course__968ce7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battlematchquestion',
            unique_together={('match', 'sequence_number')},
        ),
        migrations.AlterUniqueTogether(
            name='battlequestiongenerationchunk',
            unique_together={('source_chunk',)},
        ),
        migrations.AlterUniqueTogether(
            name='battleparticipant',
            unique_together={('room', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentquestionexposure',
            index=models.Index(fields=['student', 'last_seen_at'], name='battle_stud_student_72ac0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentquestionexposure',
            unique_together={('student', 'question')},
        ),
    ]
