# Generated by Django 6.0.6 on 2026-09-20 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
        ('core', '0027_slidetopicsplitchunk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='battlematchquestion',
            unique_together={('match', 'sequence_number', 'is_bonus')},
        ),
        migrations.CreateModel(
            name='BattleMatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1)),
                ('won', models.BooleanField(blank=True, null=True)),
                ('disconnected', models.BooleanField(default=False)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='battle.battlematch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_match_results', to='core.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'won'], name='battle_batt_student_d5cc18_idx')],
                'unique_together': {('match', 'student')},
            },
        ),
    ]
